### ISSUE TITLE
[Django] Django import 오류

### ISSUE THREAD

**Issue by yeoseon** [yeoseon/tip-archive#14]
(Windows)
Django 프로젝트에서 catalog app을 하나 생성하기 위해 가상 환경 workon 후 다음과 같은 코드를 실행했다. 
```
py -3 manage.py starapp catalog
```

다음과 같은 에러메시지를 띄우며 startapp이 실행되지 않는다.

```
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 12, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

manage.py 내에 import한 Djanog 모듈을 못찾는 모양인데,
해당 가상환경에는 Django가 받아져 있는 것도 확인했다.

**Comment by yeoseon** [comment]
```
python manage.py startapp catalog
```

로 실행하니 잘 된다. 

이유 알고나서 close 할 것

**Comment by yeoseon** [comment]
https://developer.mozilla.org/ko/docs/Learn/Server-side/Django/skeleton_website
해당 튜토리얼 사이트에서 보면
> 만약 파이썬 3.7.0 이상을 사용한다면  py manage.py startapp catalog 만을 사용하면 됩니다.

다음과 같은 안내가 있다. 이것과 같은 맥락으로 python도 지원하는 것이 아닐까 예상한다.
